/*
Authors: Theodore Tsimiklis, Peter Fishman, Saqib Syed
Date: April 28th 2021
About: This script is used to create the tables so that populate_schema can populate the tables added
*/

CREATE TABLE PERSONAL_INFO
    (
        P_INFO_ID INT PRIMARY KEY,
        ADDRESS VARCHAR2(100) NOT NULL,
        POSTAL_CODE VARCHAR2(7) NOT NULL,
        CITY VARCHAR2(50) NOT NULL,
        PHONE_NUMBER VARCHAR2(20) NOT NULL
    );

CREATE TABLE USER_ACCOUNT
    (
        USER_ACCOUNT_ID INT PRIMARY KEY,
        FIRST_NAME VARCHAR2(50) NOT NULL,
        LAST_NAME VARCHAR2(50) NOT NULL,
        USERNAME VARCHAR2(255) NOT NULL,
        USER_PASSWORD VARCHAR(50) NOT NULL
    );

CREATE TABLE CHECKOUT_CART
    (
        CHECKOUT_ID INT PRIMARY KEY,
        TOTAL_PRICE NUMBER NOT NULL,
        DISCOUNTED_PRICE NUMBER NOT NULL
    );    
    
CREATE TABLE COMPUTER_PARTS
    (
        PART_ID INT PRIMARY KEY,
        SERIAL_NUMBER INT NOT NULL,
        PRODUCT_NAME VARCHAR2(100) NOT NULL,
        COST_PRICE NUMBER NOT NULL,
        RETAIL_PRICE NUMBER NOT NULL,
        PART_INVENTORY INT NOT NULL
    );
    
CREATE TABLE RETAILER
    (
        RETAILER_ID INT PRIMARY KEY,
        RETAILER_NAME VARCHAR2(50) NOT NULL,
        INVENTORY INT NOT NULL,
        PHONE_NUMBER VARCHAR2(20) NOT NULL,
        REPRESENTATIVE VARCHAR2(50) NOT NULL,
        PRODUCT_DISCOUNT VARCHAR2(10) NOT NULL
    );
    
CREATE TABLE SALES 
    (
        SALES_ID INT PRIMARY KEY,
        ITEM_DISCOUNT NUMBER NOT NULL,
        SALE_LENGTH DATE NOT NULL
    );
    
CREATE TABLE ORDERS
    (
        ORDER_ID INT PRIMARY KEY,
        DATE_RECIEVED DATE NOT NULL,
        FINAL_PRICE NUMBER NOT NULL
    );

CREATE TABLE TRACK_ORDERS
    (
        TRACKORDER_ID INT PRIMARY KEY,
        ORDER_ETA DATE NOT NULL,
        ORDER_HAS_SHIPPED CHAR CHECK (ORDER_HAS_SHIPPED = 'Y' OR ORDER_HAS_SHIPPED = 'N')
    );
    
CREATE TABLE SHIPMENT
    (
        SHIPMENT_ID INT PRIMARY KEY,
        ORDER_ETA_DATE DATE NOT NULL,
        SHIPPING_OPTION VARCHAR(20) NOT NULL
    );

CREATE TABLE CUSTOMER_SUPPORT
    (
        CUSTOMER_SUPPORT_ID INT PRIMARY KEY,
        STORE_NAME VARCHAR2(50) NOT NULL,
        PHONE_NUMBER VARCHAR(50) NOT NULL,
        EMAIL VARCHAR(50) NOT NULL  
    );