/*
Authors: Theodore Tsimiklis, Peter Fishman, Saqib Syed
Date: April 28th 2021
About: This script is used to drop the tables
*/
DROP TABLE "PERSONAL_INFO" CASCADE CONSTRAINTS;
DROP TABLE "RETAILER" CASCADE CONSTRAINTS;
DROP TABLE "SALES" CASCADE CONSTRAINTS;
DROP TABLE "USER_ACCOUNT" CASCADE CONSTRAINTS;
DROP TABLE "ORDERS" CASCADE CONSTRAINTS;
DROP TABLE "COMPUTER_PARTS" CASCADE CONSTRAINTS;
DROP TABLE "TRACK_ORDERS" CASCADE CONSTRAINTS;
DROP TABLE "SHIPMENT" CASCADE CONSTRAINTS;
DROP TABLE "CUSTOMER_SUPPORT" CASCADE CONSTRAINTS;
DROP TABLE "CHECKOUT_CART" CASCADE CONSTRAINTS;

DROP SEQUENCE seq_order_id;
DROP SEQUENCE seq_track_order_id;
DROP SEQUENCE seq_shipment_id;
DROP SEQUENCE seq_customer_support_id;
DROP SEQUENCE seq_p_info_id;
DROP SEQUENCE seq_user_account_id;
DROP SEQUENCE seq_retailer_id;
DROP SEQUENCE seq_part_id;
DROP SEQUENCE seq_sales_id;
DROP SEQUENCE seq_checkout_id;